services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: postgres_spring-ai-products_db
    environment:
      - 'POSTGRES_DB=products'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5431:5432'
